
const Types = {

  CHANGE_ACTION_LABELS : "CHANGE_ACTION_LABELS",
  AUTHENTICATE : "AUTHENTICATE",
  AUTHENTICATED : "AUTHENTICATED",
  UNAUTHENTICATED : "UNAUTHENTICATED",
  AUTH_CHECK : "AUTH_CHECK",
  CAMERA_PERMISSION : "CAMERA_PERMISSION",
  ASK_CAMERA_PERMISSION : "ASK_CAMERA_PERMISSION",

  PARTICIPANT_COMMENT : "PARTICIPANT_COMMENT",
  PARTICIPANTS_FETCH : "PARTICIPANTS_FETCH",
  PARTICIPANTS_FETCHED : "PARTICIPANTS_FETCHED",
  PARTICIPANT_SCANNED : "PARTICIPANT_SCANNED",

  RECENTLY_SCANNED_CODE : "RECENTLY_SCANNED_CODE",
  PURGE_SCANNED : "PURGE_SCANNED",
  PURGE_COMMENTS_FOR_CODE : "PURGE_COMMENTS_FOR_CODE",
  LOGOUT : "LOGOUT",
  SYNC_REQUEST : "SYNC_REQUEST",


};


export default Types;
